apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kiteci-dns
  namespace: default
spec:
  secretName: kiteci-dns-tls
  issuerRef:
    name: letsencrypt-staging-dns
  dnsNames:
    - kiteci-dns.appscode.ninja